
package topcoders.pt.st.rt.b.s;

import topcoders.pt.st.rt.b.s.ExpenseTracker;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;

public class DisplayMonthlySummary extends javax.swing.JFrame {

    /**
     * Creates new form DisplayMonthlySummary
     */
    public DisplayMonthlySummary() {
        initComponents();
        
           // Add your KeyListeners here
    monthField.addKeyListener(new KeyAdapter() {
        @Override
        public void keyPressed(KeyEvent e) {
            if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                jButton1.doClick(); // Simulate button click
            }
        }
    });

    studIdField.addKeyListener(new KeyAdapter() {
        @Override
        public void keyPressed(KeyEvent e) {
            if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                jButton1.doClick(); // Simulate button click
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        monthField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        studIdField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        displaySummary = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Display Monthly Summary");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Display The Monthly Summary For A Specific Month");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topcoders/pt/st/rt/b/s/month.png"))); // NOI18N
        jLabel2.setText("Enter the month to search here:");

        monthField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        monthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthFieldActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topcoders/pt/st/rt/b/s/interactive-display.png"))); // NOI18N
        jButton1.setText("Display");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topcoders/pt/st/rt/b/s/user.png"))); // NOI18N
        jLabel3.setText("Enter The Student ID to display for:");

        studIdField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        displaySummary.setEditable(false);
        displaySummary.setColumns(20);
        displaySummary.setLineWrap(true);
        displaySummary.setRows(5);
        displaySummary.setWrapStyleWord(true);
        displaySummary.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(displaySummary);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topcoders/pt/st/rt/b/s/contract.png"))); // NOI18N
        jLabel4.setText("Monthly Summary:");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/topcoders/pt/st/rt/b/s/lock.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.setBorder(new javax.swing.border.MatteBorder(null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE))
                            .addComponent(monthField)
                            .addComponent(studIdField)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(62, 62, 62)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
      
        ExpenseTracker track = new ExpenseTracker();
        List<ExpenseTracker> expenses = new ArrayList<>();
        

       //Load expense records from a text file
        try
        {
            FileReader reader = new FileReader("expense.txt");
            BufferedReader  bReader = new BufferedReader(reader);
            int ch;
            StringBuilder sb = new StringBuilder();
            
            while((ch = bReader.read()) != -1)
            {
              if(ch == '\n')
              {
                String[] parts = sb.toString().split(",");
                  if (parts.length == 4) 
                  {
                    ExpenseTracker expense = new ExpenseTracker(Integer.parseInt(parts[0]),LocalDate.parse(parts[1]),Double.parseDouble(parts[2]),parts[3].trim());
                    
                    expenses.add(expense);//Add to expense list
                    
                  }
                  sb.setLength(0);
              }
              else
              {
                sb.append((char) ch);//Convert integer  ASCII to character
              }
            }
        }
        catch(IOException e)
        {
          JOptionPane.showMessageDialog(null,"Error loading expense: " + e.getMessage(),"ERROR MESSAGE",JOptionPane.ERROR);
          
        }
    
        
        if(monthField.getText().isEmpty() || studIdField.getText().isEmpty())
        {
          JOptionPane.showMessageDialog(null,"ENTER ALL THE REQUIRED FIELD(S)!!","ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            //Search for the student id in the List 
            boolean searchId = false;
            int studId = Integer.parseInt(studIdField.getText());
            for (int i = 0; i < expenses.size(); i++)
            {
                if(expenses.get(i).getStudentId() == studId)
                {
                   searchId = true;
                }
                
            }
            
            if(searchId)
            {
                //If student found continue to search for the month
               String month = monthField.getText();
               int  searchMonth = track.changeMonthFormat(month);
                month = track.changeMonthCase(month);
                
                //Search for the month entered by the user in the list for the student id entered by the use
                boolean boolSearchMon = false;
                
                for (int i = 0; i < expenses.size(); i++)
                {
                    int mon = expenses.get(i).getDate().getMonthValue();
                    if(expenses.get(i).getStudentId() == studId && mon == searchMonth)
                    {
                       boolSearchMon = true;
                    }
                
                }
            
                //If the month is found continue to get the details for the Student for that month
                if(boolSearchMon)
                {
                    
                    String output = "Monthly Summary for the Student ID: " + studId + " for the month: "+ month + "\n================================================";
                    double total = 0;
                 
                    //Checks if there is more than one input for that student and for that month
                    for (int i = 0; i < expenses.size(); i++) 
                    {
                       
                      int mon = expenses.get(i).getDate().getMonthValue();

                        if(expenses.get(i).getStudentId() == studId && mon == searchMonth)
                        {
                           total += expenses.get(i).getAmount(); 
                           output +=  "\nCategory: " + expenses.get(i).getCategory() + "\nExpense: R"+expenses.get(i).getAmount()+ "\n";

                        }

                     }
                   
                     output += "===========================================";
                     output += "\nTotal for month "+ month + ": R" + total;
                     output += "\n===========================================";
                    
                    monthField.setText("");
                    studIdField.setText("");
                    displaySummary.setText(output);
                    displaySummary.requestFocusInWindow();
                }
                else
                {
                 
                    displaySummary.setText("Month " + month + " does not exit for the Student Id:" + studId);
                }
                     
            }
            else
            {
              
              displaySummary.setText("Student ID " + studId + " was not found in the database.");
            }
                  
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayMonthlySummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayMonthlySummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayMonthlySummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayMonthlySummary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayMonthlySummary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea displaySummary;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField monthField;
    private javax.swing.JTextField studIdField;
    // End of variables declaration//GEN-END:variables
}
